In [3]:
import numpy as np
two_by_two_ones = np.ones((2,2))
print(two_by_two_ones)
four_by_four_id = np.eye(4)
print(four_by_four_id)

[[ 1.  1.]
 [ 1.  1.]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [6]:
move_by_3 = np.arange(0, 100, 2.99)
print(move_by_3)

[  0.     2.99   5.98   8.97  11.96  14.95  17.94  20.93  23.92  26.91
  29.9   32.89  35.88  38.87  41.86  44.85  47.84  50.83  53.82  56.81
  59.8   62.79  65.78  68.77  71.76  74.75  77.74  80.73  83.72  86.71
  89.7   92.69  95.68  98.67]


In [13]:
crazy_eights = np.full((8,8),8)
print(type(crazy_eights))
print(crazy_eights)

<class 'numpy.ndarray'>
[[8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]]


In [15]:
crazy_eights.shape

(8, 8)